export const awardItems = [
  {
    id: 1,
    src: '/images/awards/bloomberg_gender_equality.svg',
    title: 'Bloomberg Magazine',
    award: 'Named to the 2020 Bloomberg Gender-Equality Index (GEI)',
    desc: "For the fourth consecutive year, we're named to Fortune's list of the 100 Best Companies to Work For. This prestigious recognition comes after we participated in the Great Place to Work Trust Index Employee Survey, in which employees from across the organization provided anonymous feedback about our company. We are no. 40 on Fortune's final list",
    alt: 'GEI Logo',
    cname: 'award--logo',
  },
  {
    id: 2,
    src: '/images/awards/diversityinc-top-10.svg',
    title: 'Diversity Inc.',
    award: 'Named the top financial service company for diversity',
    desc: "For the fourth consecutive year, we're named to Fortune's list of the 100 Best Companies to Work For. This prestigious recognition comes after we participated in the Great Place to Work Trust Index Employee Survey, in which employees from across the organization provided anonymous feedback about our company. We are no. 40 on Fortune's final list",
    alt: 'Diversity Inc.',
    cname: 'award--logo',
  },
  {
    id: 3,
    src: '/images/awards/fortune-most-admired.svg',
    title: 'Fortune Magazine',
    award: "World's Most Admired Companies 2020",
    desc: "For the fourth consecutive year, we're named to Fortune's list of the 100 Best Companies to Work For. This prestigious recognition comes after we participated in the Great Place to Work Trust Index Employee Survey, in which employees from across the organization provided anonymous feedback about our company. We are no. 40 on Fortune's final list",
    alt: 'Fortune Logo',
    cname: 'award--logo',
  },
  {
    id: 4,
    src: '/images/awards/Forbes-Best-Small.svg',
    title: 'Forbes Magazine',
    award: '2020 Best Small Companies',
    desc: "For the fourth consecutive year, we're named to Fortune's list of the 100 Best Companies to Work For. This prestigious recognition comes after we participated in the Great Place to Work Trust Index Employee Survey, in which employees from across the organization provided anonymous feedback about our company. We are no. 40 on Fortune's final list",
    alt: 'Forbes Logo',
    cname: 'award--logo',
  },
  {
    id: 5,
    src: '/images/awards/fortune.svg',
    title: "Fortune's 100 Best Companies to Work For",
    award: "Recognized as one of Canada's Top 100 Employers for 2020",
    desc: "For the fourth consecutive year, we're named to Fortune's list of the 100 Best Companies to Work For. This prestigious recognition comes after we participated in the Great Place to Work Trust Index Employee Survey, in which employees from across the organization provided anonymous feedback about our company. We are no. 40 on Fortune's final list",
    alt: 'Mediacorp Logo',
    cname: 'award--logo',
  },
  {
    id: 6,
    src: '/images/awards/bloomberg-leadership.svg',
    title: 'Bloomberg Businessweek',
    award: '2020 Best Companies For Leadership',
    desc: "For the fourth consecutive year, we're named to Fortune's list of the 100 Best Companies to Work For. This prestigious recognition comes after we participated in the Great Place to Work Trust Index Employee Survey, in which employees from across the organization provided anonymous feedback about our company. We are no. 40 on Fortune's final list",
    alt: 'Bloomberg Logo',
    cname: 'award--logo',
  },
  {
    id: 7,
    src: '/images/awards/forbes-innovative.svg',
    title: 'Forbes Magazine',
    award: "World's Most Innovative Companies",
    desc: "For the fourth consecutive year, we're named to Fortune's list of the 100 Best Companies to Work For. This prestigious recognition comes after we participated in the Great Place to Work Trust Index Employee Survey, in which employees from across the organization provided anonymous feedback about our company. We are no. 40 on Fortune's final list",
    alt: 'Forbes  Logo',
    cname: 'award--logo',
  },
  {
    id: 8,
    src: '/images/awards/best_workplace.svg',
    title: 'Great Place To Work',
    award: 'Best Workplaces in Texas',
    desc: "For the fourth consecutive year, we're named to Fortune's list of the 100 Best Companies to Work For. This prestigious recognition comes after we participated in the Great Place to Work Trust Index Employee Survey, in which employees from across the organization provided anonymous feedback about our company. We are no. 40 on Fortune's final list",
    alt: 'Mediacorp Logo',
    cname: 'award--logo',
  },
];
