export const focusItems = [
    {
      id: 1,
      src: '/images/icons/team.svg',
      headline: 'Collaboration',
      class: 'one',
      alt: 'Team Icon',
      desc: 'World Class Teams  Most of our job is finding and supporting great teams. If we can do that well, the rest typically takes care of itself',
      bgColor: '#BB8760',
      txtColor: '#050E13',
    },
    {
      id: 2,
      src: '/images/icons/startup.svg',
      headline: 'Start Up Companies',
      class: 'two',
      alt: 'Startup Icon',
      desc: 'Start up companies can be defined in many different ways. In our mind, the question is no longer, “How can we get this company off the ground?” but rather, “How can we maximize its potential?”.',
      bgColor: '#BB8760',
      txtColor: '#050E13',
    },
    {
      id: 3,
      src: '/images/icons/sector.svg',
      headline: 'Sector Experts',
      class: 'three',
      alt: 'Sector Icon',
      desc: 'We play in areas that we know well from years of focused investing. We apply the full breadth of our knowledge and networks to advance the interests of our portfolio companies.',
      bgColor: '#BB8760',
      txtColor: '#050E13',
    },
    {
      id: 4,
      src: '/images/icons/flexible.svg',
      headline: 'Flexible Investment Structure',
      class: 'four',
      alt: 'Investment Icon',
      desc: 'We tailor deal structures to accomplish a company’s objectives, rather than force deal terms to fit an arbitrary investment box.',
      bgColor: '#BB8760',
      txtColor: '#050E13',
    },
    {
      id: 5,
      src: '/images/icons/fundamentals.svg',
      headline: 'Sound Fundamentals',
      class: 'five',
      alt: 'Fundamentals Icon',
      desc: 'While the relevant metrics are different for every business, we believe that great, enduring companies can only be built on solid fundamentals.',
      bgColor: '#BB8760',
      txtColor: '#050E13',
    },
    {
      id: 6,
      src: '/images/icons/tech.svg',
      headline: 'Tech Opportunities',
      class: 'six',
      alt: 'Fundamentals Icon',
      desc: 'Partnering with tech companies to unlock their full potential We partner with exceptional entrepreneurs and managementeams to help them succeed through critical phases of growth and expansion.',
      bgColor: '#BB8760',
      txtColor: '#050E13',
    },
  ];