export const principlesItems = [
  {
    id: 1,
    src: '/images/icons/science.svg',
    strategy: 'Science',
    class: 'one',
    desc: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor.',
    bgColor: '#BB8760',
    txtColor: '#050E13',
  },
  {
    id: 2,
    src: '/images/icons/healthcare.svg',
    strategy: 'Healthcare',
    class: 'two',
    desc: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor.',
    direction: 'row-reverse',
    bgColor: '#050E13',
    txtColor: '#BB8760',
  },
  {
    id: 3,
    src: '/images/icons/cleanEnergy.svg',
    strategy: 'Energy',
    class: 'three',
    desc: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor.',
    bgColor: '#BB8760',
    txtColor: '#050E13',
  },
  {
    id: 4,
    src: '/images/icons/crypto.svg',
    strategy: 'Crypto',
    class: 'four',
    desc: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor.',
    direction: 'row-reverse',
    bgColor: '#050E13',
    txtColor: '#BB8760',
  },
  {
    id: 5,
    src: 'images/icons/telecom.svg',
    strategy: 'Telecom',
    class: 'five',
    desc: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor.',
    bgColor: '#050E13',
    txtColor: '#BB8760',
  },
  {
    id: 6,
    src: 'images/icons/crane.svg',
    strategy: 'Infrastructure',
    class: 'six',
    desc: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor.',
    direction: 'row-reverse',
    bgColor: '#BB8760',
    txtColor: '#050E13',
  },
];
