export {default as AboutPage} from './About'
export {default as HomePage} from './Home'
export {default as ContactPage} from './Contact'
export {default as ApproachPage} from './Approach'
export {default as FundsPage} from './Funds'
export {default as TeamsPage} from './Teams'